import React, {useEffect, useRef, useState} from 'react';
import {ArrowRight, ArrowUpRight, Check, ChevronLeft, Clock3, Moon, Plus, Search, Sun, X, MoreHorizontal, CalendarDays, CircleDot, Sparkles, Menu} from 'lucide-react';
import { isSupabaseConfigured, supabase } from '../lib/supabase';

const threads = [
 {id:1, name:'Maya Sharma', subtitle:'Potential collaboration', initials:'MS', color:'#d9dad1', when:'2 days ago', context:'Discussed a potential collaboration after their upcoming product launch.', next:'Follow up after launch', status:'Needs attention soon', group:'attention', person:'Maya Sharma', timeline:[['September 2','Meeting','Discussed collaboration possibilities around the upcoming launch.'],['September 2','Commitment','Send product overview and a short deck.'],['September 5','Follow-up','Check in after product launch.']]},
 {id:2, name:'Northstar Labs', subtitle:'Potential client', initials:'NL', color:'#dce1ec', when:'Yesterday', context:'They are comparing approaches for their next product launch.', next:'Send revised proposal', status:'Overdue', group:'attention', person:'Northstar Labs', timeline:[['August 25','Call','Walked through the scope and early product questions.'],['August 27','Commitment','Revise proposal with a phased plan.'],['September 1','Follow-up','Send revised proposal.']]},
 {id:3, name:'Arjun Mehta', subtitle:'Freelance project', initials:'AM', color:'#e7ddd2', when:'4 days ago', context:'The contract is with their legal team for review.', next:'Wait for contract feedback', status:'Waiting', group:'waiting', person:'Arjun Mehta', timeline:[['August 29','Meeting','Aligned on scope and timeline for the first phase.'],['August 30','Follow-up','Sent draft agreement.'],['September 3','Waiting','Waiting on their contract feedback.']]},
 {id:4, name:'Sarah Chen', subtitle:'Product advisor', initials:'SC', color:'#d9e5df', when:'12 days ago', context:'Shared thoughtful feedback about the onboarding experience.', next:'Reconnect on her feedback', status:'Going quiet', group:'quiet', person:'Sarah Chen', timeline:[['August 18','Conversation','Discussed onboarding feedback and the first ten minutes of user experience.'],['August 19','Note','She recommended simplifying the activation moment.'],['August 21','Follow-up','Reconnect once the changes are live.']]},
 {id:5, name:'Rohan Kapoor', subtitle:'Coffee conversation', initials:'RK', color:'#e5dce6', when:'18 days ago', context:'Met at the Delhi product meetup and spoke about hiring.', next:'Reconnect regarding hiring', status:'Going quiet', group:'quiet', person:'Rohan Kapoor', timeline:[['August 12','Coffee','Met at Delhi product meetup.'],['August 12','Conversation','Discussed early product hiring.'],['August 16','Follow-up','Reconnect when there is a role to discuss.']]}
];

const fragments=['Follow up with Maya','Send revised proposal','Client call — Thursday','Discuss hiring timeline','Waiting for feedback','Coffee with Arjun','Budget approval','Circle back next week','Promised to send deck','Partnership conversation','Check in after launch','Investor introduction','Need to reply','Discuss contract','Product feedback','Follow-up overdue','Met at conference','Send meeting notes','Potential collaboration','Waiting on their response','Reconnect?','Next steps unclear','Client went quiet','Review proposal'];
const paths=['M-40 90 C 180 20, 260 210, 460 125 S 700 20, 940 155','M-20 218 C 185 80, 285 310, 475 195 S 735 100, 1010 255','M-30 320 C 150 235, 348 390, 515 270 S 756 215, 980 345','M-40 450 C 190 315, 310 560, 534 430 S 720 345, 1000 490','M-25 560 C 175 470, 330 665, 510 545 S 770 460, 1015 640','M-30 710 C 145 560, 326 775, 520 650 S 745 580, 1010 745','M-50 845 C 145 730, 340 920, 530 805 S 760 700, 1020 880','M-20 40 C 220 185, 320 20, 535 120 S 760 290, 1020 80'];

function ThemeToggle({dark,setDark}) { return <button className="theme-toggle" onClick={()=>setDark(!dark)} aria-label="Toggle dark mode">{dark?<Sun size={15}/>:<Moon size={15}/>}<span>{dark?'Light':'Dark'}</span></button> }
function Mark(){ return <span className="mark"><i></i><i></i><i></i></span> }

function HeroThreads(){
 const ref=useRef(null);
 const move=e=>{const r=ref.current?.getBoundingClientRect();if(r){ref.current.style.setProperty('--px',((e.clientX-r.left)/r.width-.5)*18+'px');ref.current.style.setProperty('--py',((e.clientY-r.top)/r.height-.5)*18+'px')}};
 return <div className="hero-threads" ref={ref} onPointerMove={move} onPointerLeave={()=>{ref.current?.style.setProperty('--px','0px');ref.current?.style.setProperty('--py','0px')}} aria-hidden="true"><span className="thread-label label-one">a promise</span><span className="thread-label label-two">a next step</span><svg viewBox="0 0 570 530" fill="none"><defs><filter id="soft"><feGaussianBlur stdDeviation=".22"/></filter></defs><g className="thread-shift"><path className="hero-thread ht1" d="M-38 184C64 76 142 264 239 159C328 63 363 18 486 117C539 160 566 113 613 59"/><path className="hero-thread ht2" d="M-26 304C84 233 143 405 244 291C335 190 353 354 467 279C524 242 538 325 604 408"/><path className="hero-thread ht3" d="M31 462C94 345 171 411 218 346C275 267 349 470 419 385C474 317 535 409 598 335"/><path className="hero-thread ht4" d="M-4 99C98 140 133 77 215 92C302 107 317 221 397 213C469 206 489 165 573 186"/><path className="hero-thread ht5" d="M71 526C104 420 64 346 162 289C226 252 283 246 295 156C305 89 378 62 439 84"/><circle className="node n1" cx="239" cy="159" r="4"/><circle className="node n2" cx="467" cy="279" r="4"/><circle className="node n3" cx="218" cy="346" r="3.5"/><circle className="traveller t1" r="3"><animateMotion dur="8s" repeatCount="indefinite" path="M-38 184C64 76 142 264 239 159C328 63 363 18 486 117C539 160 566 113 613 59"/></circle><circle className="traveller t2" r="2.5"><animateMotion dur="10s" begin="-4s" repeatCount="indefinite" path="M-26 304C84 233 143 405 244 291C335 190 353 354 467 279C524 242 538 325 604 408"/></circle></g></svg></div>
}

function Landing({setScreen,dark,setDark}) {
 const [menu,setMenu]=useState(false);
 return <main className="landing">
  <nav className="landing-nav"><button className="brand" onClick={()=>setScreen('landing')}><Mark/>Threadwise</button><div className="nav-middle"><a href="#story">How it works</a><a href="#product">Product</a></div><div className="nav-actions"><ThemeToggle dark={dark} setDark={setDark}/><button className="text-button" onClick={()=>setScreen('login')}>Log in</button><button className="ink-button small" onClick={()=>setScreen('signup')}>Sign up</button></div><button className="mobile-menu" onClick={()=>setMenu(!menu)}><Menu size={20}/></button>{menu&&<div className="mobile-nav"><a href="#story" onClick={()=>setMenu(false)}>How it works</a><a href="#product" onClick={()=>setMenu(false)}>Product</a><button onClick={()=>setScreen('login')}>Log in</button><button onClick={()=>setScreen('signup')}>Sign up</button></div>}</nav>
  <section className="hero"><div className="hero-copy"><p className="eyebrow">A memory system for your work</p><h1>Lost in your<br/><em>follow-ups...</em> again?</h1><p className="hero-sub">Conversations move. Promises get buried. Important people slip between meetings, messages, and everything else.</p><button className="line-cta" onClick={()=>document.querySelector('#story').scrollIntoView({behavior:'smooth'})}>Find your threads <ArrowRight size={17}/></button><p className="quiet-note">A calmer way to remember what needs your attention.</p></div><HeroThreads/></section>
  <section id="story" className="thread-story"><div className="story-sticky"><svg className="thread-canvas" viewBox="0 0 1000 920" preserveAspectRatio="none">{paths.map((p,i)=><path key={p} className={'thread-path p'+i} d={p}/>)}</svg>{fragments.map((f,i)=><span key={f} className={'fragment f'+i}>{f}</span>)}<div className="void"><div></div></div><div className="story-copy story-one"><p className="eyebrow">01 / the beginning</p><h2>It starts with<br/>one conversation.</h2><p>A meeting. A promise. A quick message saying, “Let’s reconnect next week.”</p></div><div className="story-copy story-two"><p className="eyebrow">02 / the buildup</p><h2>Then life<br/>keeps moving.</h2><p>Meetings overlap. Conversations continue. New people enter the picture.</p></div><div className="story-copy story-three"><p className="eyebrow">03 / the tangle</p><h2>And somehow,<br/>the important things<br/>get buried.</h2><p>Not because they weren’t important. Because there was nowhere to hold the thread.</p></div><div className="story-copy story-four"><p>Some conversations shouldn’t disappear.</p><h2>Threadwise remembers<br/>where you left off.</h2></div></div></section>
  <section id="product" className="product-intro"><p className="eyebrow">CHAOS → CLARITY</p><h2>Your conversations.<br/><em>Finally connected.</em></h2><p>Threadwise gives every important relationship a place to live. Along with its context, history, and next step.</p><button className="ink-button" onClick={()=>setScreen('signup')}>Begin with your threads <ArrowRight size={16}/></button><MiniProduct/></section>
  <footer><button className="brand"><Mark/>Threadwise</button><p>Keep track of what matters between conversations.</p><button className="text-button" onClick={()=>setScreen('signup')}>Get started <ArrowUpRight size={15}/></button></footer>
 </main>
}

function MiniProduct(){return <div className="mini-product"><div className="mini-side"><Mark/><span>Attention</span><span>Threads</span><span>People</span></div><div className="mini-main"><p className="eyebrow">ATTENTION SPACE</p><h3>What needs your attention?</h3><div className="mini-thread"><b>Maya Sharma</b><span>Potential collaboration</span><p>Follow up after launch <ArrowRight size={13}/></p></div><div className="mini-thread"><b>Northstar Labs</b><span>Potential client</span><p>Send revised proposal <ArrowRight size={13}/></p></div></div></div>}

function Auth({kind,setScreen,dark,setDark}){
 const signup=kind==='signup'; const [email,setEmail]=useState(''); const [code,setCode]=useState(''); const [sent,setSent]=useState(false); const [loading,setLoading]=useState(false); const [error,setError]=useState('');
 const sendCode=async()=>{setError(''); if(!supabase){setError('Add your Supabase environment variables first.');return} if(!email.trim()){setError('Enter your email address.');return} setLoading(true);const {error}=await supabase.auth.signInWithOtp({email,options:{shouldCreateUser:signup}});setLoading(false);if(error)setError(error.message);else setSent(true)};
 const verifyCode=async()=>{setError('');if(!supabase)return;setLoading(true);const {error}=await supabase.auth.verifyOtp({email,token:code,type:'email'});setLoading(false);if(error)setError(error.message);else setScreen('app')};
 const google=async()=>{setError('');if(!supabase){setError('Add your Supabase environment variables first.');return}setLoading(true);const {data,error}=await supabase.auth.signInWithOAuth({provider:'google',options:{redirectTo:`${window.location.origin}/auth/popup-callback`,skipBrowserRedirect:true}});if(error||!data?.url){setLoading(false);setError(error?.message||'Unable to start Google sign-in.');return}const popup=window.open(data.url,'threadwise-google-auth','width=500,height=650,menubar=no,toolbar=no,status=no');setLoading(false);if(!popup)setError('Please allow popups to continue with Google.')};
 return <div className="auth"><nav className="auth-nav"><button className="brand" onClick={()=>setScreen('landing')}><Mark/>Threadwise</button><ThemeToggle dark={dark} setDark={setDark}/></nav><div className="auth-frame"><p className="eyebrow">{signup?'BEGIN A CALMER WAY OF WORKING':'WELCOME BACK'}</p><h1>{sent?'Check your email.':signup?'Keep the thread.':'Pick up where you left off.'}</h1><p>{sent?`We sent a 6-digit code to ${email}. Enter it below to continue.`:signup?'Start giving your important conversations a home.':'Your conversations and context are right where you left them.'}</p>{!sent&&<><div className="oauth"><button onClick={google} disabled={loading}><span className="google">G</span>{loading?'Opening Google…':'Continue with Google'}</button></div><div className="or"><i/>or continue with email<i/></div></>}{sent?<><label>6-digit code<input className="otp-input" autoFocus inputMode="numeric" maxLength="6" placeholder="000000" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,''))}/></label><button className="ink-button full" disabled={loading||code.length!==6} onClick={verifyCode}>{loading?'Verifying…':'Verify and continue'} <ArrowRight size={16}/></button><button className="resend" disabled={loading} onClick={sendCode}>Resend code</button><button className="resend" onClick={()=>{setSent(false);setCode('');setError('')}}>Use a different email</button></>:<><label>Email address<input autoFocus placeholder="you@example.com" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><button className="ink-button full" disabled={loading} onClick={sendCode}>{loading?'Sending code…':'Continue with email'} <ArrowRight size={16}/></button><p className="auth-switch">{signup?'Already have an account?':'New to Threadwise?'} <button onClick={()=>setScreen(signup?'login':'signup')}>{signup?'Log in':'Sign up'}</button></p></>}{error&&<p className="auth-error" role="alert">{error}</p>}<button className="back" onClick={()=>setScreen('landing')}><ChevronLeft size={15}/> Back to Threadwise</button></div></div>}

function App({setScreen}){const [active,setActive]=useState('Attention');const [selected,setSelected]=useState(null);const [capture,setCapture]=useState(false);const [query,setQuery]=useState('');const matches=threads.filter(t=>(t.name+t.subtitle).toLowerCase().includes(query.toLowerCase())); if(selected) return <Detail item={selected} back={()=>setSelected(null)} />;return <div className="app-shell"><aside><button className="brand app-brand" onClick={()=>setScreen('landing')}><Mark/>Threadwise</button><nav>{[['Attention',CircleDot],['Threads',Clock3],['People',Search]].map(([x,I])=><button className={active===x?'active':''} key={x} onClick={()=>setActive(x)}><I size={16}/>{x}</button>)}</nav><button className="capture-button" onClick={()=>setCapture(true)}><Plus size={16}/> Capture</button><div className="profile"><span>AT</span><div><b>Arnav Thakur</b><small>Personal workspace</small></div><MoreHorizontal size={16}/></div></aside><main className="app-content"><header><div><p className="eyebrow">{active==='Attention'?'TUESDAY, SEPTEMBER 8':active.toUpperCase()}</p><h1>{active==='Attention'?'What needs your attention?':active}</h1></div><button className="mobile-capture" onClick={()=>setCapture(true)}><Plus size={17}/></button></header>{active==='Attention'&&<Attention data={threads} open={setSelected}/>} {active==='Threads'&&<AllThreads data={matches} query={query} setQuery={setQuery} open={setSelected}/>} {active==='People'&&<People data={threads} open={setSelected}/>}</main>{capture&&<Capture close={()=>setCapture(false)} open={setSelected}/>}</div>}
function ThreadCard({item,open}){return <button className="thread-card" onClick={()=>open(item)}><div className="avatar" style={{background:item.color}}>{item.initials}</div><div className="thread-card-main"><div className="card-title"><h3>{item.name}</h3><span>{item.when}</span></div><p className="subtitle">{item.subtitle}</p><p className="context">{item.context}</p><div className="next"><span>Next</span>{item.next}<ArrowRight size={14}/></div></div><div className={'status '+item.group}>{item.status}</div></button>}
function Attention({data,open}){const groups=[['Needs attention',data.filter(x=>x.group==='attention'),'A few threads need a gentle nudge.'],['Waiting',data.filter(x=>x.group==='waiting'),'You’re waiting on someone else.'],['Going quiet',data.filter(x=>x.group==='quiet'),'These conversations have been quiet for a while.']];return <div className="attention">{groups.map(([title,items,note])=><section className="attention-group" key={title}><div className="group-header"><h2>{title}<small>{items.length}</small></h2><p>{note}</p></div>{items.map(item=><ThreadCard key={item.id} item={item} open={open}/>)}</section>)}</div>}
function AllThreads({data,query,setQuery,open}){return <><div className="search"><Search size={16}/><input autoFocus placeholder="Search threads" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="thread-grid">{data.map(item=><ThreadCard key={item.id} item={item} open={open}/>)}</div></>}
function People({data,open}){return <div className="people-list">{data.map(x=><button key={x.id} onClick={()=>open(x)}><span className="avatar" style={{background:x.color}}>{x.initials}</span><div><h3>{x.person}</h3><p>{x.subtitle} · Last interaction {x.when}</p></div><span className={'status '+x.group}>{x.status}</span><ArrowRight size={16}/></button>)}</div>}
function Detail({item,back}){return <div className="detail"><header><button className="back-detail" onClick={back}><ChevronLeft size={17}/> All threads</button><button className="more"><MoreHorizontal size={19}/></button></header><section className="detail-hero"><div className="avatar large" style={{background:item.color}}>{item.initials}</div><div><p className="eyebrow">{item.subtitle}</p><h1>{item.name}</h1><span className="active-status"><i/> Active</span></div></section><div className="detail-layout"><section className="timeline"><h2>The thread so far</h2>{item.timeline.map(([date,type,text],i)=><div className="event" key={type}><div><span></span>{i<item.timeline.length-1&&<i/>}</div><article><p className="event-date">{date}</p><h3>{type}</h3><p>{text}</p></article></div>)}</section><aside className="next-step"><p className="eyebrow">NEXT STEP</p><h2>{item.next}</h2><p>This thread needs a little attention.</p><button className="ink-button"><Check size={15}/> Mark complete</button><button>Reschedule</button><button>Edit thread</button></aside></div></div>}
function Capture({close,open}){const [text,setText]=useState('');const [saved,setSaved]=useState(false);return <div className="modal-wrap" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="capture-modal"><button className="modal-close" onClick={close}><X size={19}/></button>{saved?<div className="saved"><span><Check size={22}/></span><p className="eyebrow">CAPTURED</p><h2>Context saved to Maya’s thread.</h2><p>Your note is now part of the conversation, alongside its history and next step.</p><button className="ink-button" onClick={()=>{close();open(threads[0])}}>Open thread <ArrowRight size={16}/></button></div>:<><p className="eyebrow">QUICK CAPTURE</p><h2>Before it slips away.</h2><p className="modal-intro">Write down a conversation, promise, or anything you want to remember.</p><textarea autoFocus value={text} onChange={e=>setText(e.target.value)} placeholder="Talked to Maya today. She's launching next Friday and asked me to send the product deck afterwards."/><div className="capture-footer"><span>It will be saved to a thread you choose.</span><button className="ink-button" disabled={!text.trim()} onClick={()=>setSaved(true)}>Capture <ArrowRight size={16}/></button></div></>}</div></div>}
export default function Root(){const [screen,setScreen]=useState('landing');const [dark,setDark]=useState(false);useEffect(()=>{document.documentElement.dataset.theme=dark?'dark':'light'},[dark]);useEffect(()=>{if(!isSupabaseConfigured)return;const restore=async()=>{const {data:{session}}=await supabase.auth.getSession();if(session)setScreen('app')};restore();const {data:{subscription}}=supabase.auth.onAuthStateChange((_event,session)=>{if(session)setScreen('app')});const message=async(event)=>{if(event.origin!==window.location.origin||event.data?.type!=='threadwise-google-complete')return;const {data:{session}}=await supabase.auth.getSession();if(session)setScreen('app')};window.addEventListener('message',message);return()=>{subscription.unsubscribe();window.removeEventListener('message',message)}} ,[]);return screen==='landing'?<Landing setScreen={setScreen} dark={dark} setDark={setDark}/>:screen==='app'?<App setScreen={setScreen}/>:<Auth kind={screen} setScreen={setScreen} dark={dark} setDark={setDark}/>}
